### ISSUE TITLE
Tutorial 3: failed to run in google colab

### ISSUE THREAD

**Issue by YiyiAm** [bentrevett/pytorch-seq2seq#159]
I tried to run tutorial 3 in google colab

It succeeded many days ago, but not today. 
I encountered an odd bug in the following code:
    from torchtext.datasets import TranslationDataset, Multi30k

ImportError: cannot import name 'TranslationDataset' from 'torchtext.datasets' 
(/usr/local/lib/python3.7/dist-packages/torchtext/datasets/__init__.py)

These codes ran well:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

What's wrong?

**Comment by YiyiAmoy** [comment]
funny, this problem has been solved by:
!pip uninstall torchtext
!pip install torchtext

and now the version is:
torch==1.8.0
torchtext-0.9.0

**Comment by YiyiAm** [comment]
failed again with nothing changed, except for a reconnection

still not figure out what's happing , sad

**Comment by YiyiAm** [comment]
## always follow this sequence:
## first connect and set GPU

## run these:
# !pip uninstall torchtext
# !pip install -U torchtext==0.8.0
## agree to restart，
## run your pytorch program first，and see ： xxx undefined

## then run these：
# !pip uninstall torchtext
# !pip install torchtext 
## agree to restart

## then run these
# !python -m spacy download en 
# !python -m spacy download de
## then you can run the code normally
## reason unknown

**Comment by bentrevett** [comment]
These bugs are because of some big API changes in torchtext between versions 0.8 and 0.9. 

I need to update the tutorials appropriately, but haven't yet had the chance to do so. I will work on it this weekend.

**Comment by YiyiAm** [comment]
> 
> 
> These bugs are because of some big API changes in torchtext between versions 0.8 and 0.9.
> 
> I need to update the tutorials appropriately, but haven't yet had the chance to do so. I will work on it this weekend.

Thank you

**Comment by bentrevett** [comment]
This should be updated now. The `master` branch should work with torchtext 0.9 and PyTorch 1.8 and the `torchtext08` branch should work with torchtext 0.8 and PyTorch 1.7.

Please let me know if encounter any more errors and I'll try and fix them ASAP.

**Comment by bentrevett** [comment]
This should now be fixed. 

If you're using PyTorch 1.8 and torchtext 0.9 then the `master` branch should work.

If you're using PyTorch 1.7 and torchtext 0.8 then the `torchtext08` branch should work.

Please let me know if you encounter any more issues and I'll try and fix them ASAP.
